version: org.riotkit.rkd/yaml/v1
imports:
    - rkd.php.script.PhpScriptTask

tasks:
    :yaml:test:php:
        extends: rkd.php.script.PhpScriptTask
        configure@before_parent: |
            self.version = '7.2-alpine'
        inner_execute@after_parent: |
            print('IM AFTER PARENT')
            return True
        input: |
            var_dump(getcwd());
            var_dump(phpversion());

    :yaml:test:multi:
        steps:
            - |
                #!bash
                echo "Hello world from Bash"
